# Generated by Django 3.2.6 on 2021-09-04 22:18
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations

def create_superboss(apps,schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    User.objects.create(
        username='giuseppi',
        email='giuseppi@gmail.com',
        password=make_password('giuseppi')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superboss)
    ]
