# Generated by Django 3.2.6 on 2021-09-04 22:18

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password

data_bosses = [
    {'username':'boss1', 'email': 'boss1@gmail.com', 'password':'12345'},
    {'username':'boss2', 'email': 'boss2@gmail.com', 'password':'12345'},
    {'username':'boss3', 'email': 'boss3@gmail.com', 'password':'12345'}
]

def create_bosses(apps,schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Boss = apps.get_model('accounts', 'Boss')

    for boss in data_bosses:        
        user = User.objects.create(
            username=boss['username'],
            email=boss['email'],
            password=make_password(boss['password'])
        )

        Boss.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
    ]

    operations = [
        migrations.RunPython(create_bosses)
    ]
