# Generated by Django 3.2.6 on 2021-09-04 22:27

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password

status_data = [
    {'name': 'Unassigned', 'code':'none'},
    {'name': 'Assigned', 'code':'0'},
    {'name': 'Completed', 'code':'1'},
    {'name': 'Failed', 'code':'-1'}, 
    {'name': 'Active', 'code':'on'},
    {'name': 'Inactive', 'code':'off'}
    #{'name': 'Dead', 'code':'dead'
]

def create_status(apps,schema_editor):
    State = apps.get_model('accounts', 'State')

    for status in status_data:
        State.objects.create(name=status['name'],code=status['code'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_boss'),
    ]

    operations = [
        migrations.RunPython(create_status),
    ]
