# Generated by Django 3.2.6 on 2021-09-04 22:27

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password

data_hitmans = [
    {'username':'hitman1', 'email': 'hitman1@gmail.com', 'password':'12345'},
    {'username':'hitman2', 'email': 'hitman2@gmail.com', 'password':'12345'},
    {'username':'hitman3', 'email': 'hitman3@gmail.com', 'password':'12345'},
    {'username':'hitman4', 'email': 'hitman4@gmail.com', 'password':'12345'},
    {'username':'hitman5', 'email': 'hitman5@gmail.com', 'password':'12345'},
    {'username':'hitman6', 'email': 'hitman6@gmail.com', 'password':'12345'},
    {'username':'hitman7', 'email': 'hitman7@gmail.com', 'password':'12345'},
    {'username':'hitman8', 'email': 'hitman8@gmail.com', 'password':'12345'},
    {'username':'hitman9', 'email': 'hitman9@gmail.com', 'password':'12345'}
]

def create_hitmans(apps,schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Hitman = apps.get_model('accounts', 'Hitman')
    State = apps.get_model('accounts', 'State')

    for hitman in data_hitmans:
        user = User.objects.create(
            username=hitman['username'],
            email=hitman['email'],
            password=make_password(hitman['password'])
        )

        status=State.objects.get(code='none')        
        
        Hitman.objects.create(user=user, status=status)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_status'),
    ]

    operations = [
        migrations.RunPython(create_hitmans)
    ]
